### PR TITLE
Bump VERSION variable to match tag

### PR DESCRIPTION
**Pull request by szero**
Adresses #20, updated the tag too but not sure if it can be part of pull request

### CODE REVIEW

**Comment by szero** [comment]
yea git tag -f 1.2.2 has to be done and force pushed after this gets accepted

**Comment by teleshoes** [comment]
oops, thanks. i dont think its great to change a tag's commit hash, so maybe i wont :/

**Comment by szero** [comment]
right, distros have pulled this already and i guess it doesnt matter much if they build a package against tag vs specific commit

**Comment by teleshoes** [comment]
on further reflection, its better to update the tag. if a user or a build system gets confused by it, the only difference in the code is VERSION, which would have confused them anyway

**Pull request merged**
